[tool.poetry]
name = "translate-landofsika"
version = "0.1.0"
description = ""
authors = ["thomas_soutif"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
